### ISSUE TITLE
Help Swift

### ISSUE THREAD

**Issue by pagedimka** [txty-io/texterify#153]
Hello! Tell me how to solve this problem in Swift? I have contacted you by email, but there is no response from you
https://github.com/txty-io/texterify-ios/issues/3

**Comment by chrztoph** [comment]
Hey, I will have a look at your problem at start of next week.
Sorry for the troubles right now.

**Comment by pagedimka** [comment]
Thanks! I will be waiting for your answer)

**Comment by pagedimka** [comment]
> Hey, I will have a look at your problem at start of next week.
> 
> Sorry for the troubles right now.

Hello!  you did not forget about my question and the solution to the problem?

**Comment by chrztoph** [comment]
Hey, issue should be fixed now.
Closing this in favor of https://github.com/txty-io/texterify-ios/issues/3.
