### ISSUE TITLE
Problem with compile and installation.

### ISSUE THREAD

**Issue by ZbruczIT** [txty-io/texterify#159]
I don't know if I'm doing everything right, but I'm having troubles with installing the new version of texterify.
Previously I installed texterify via Docker but it's not updated to the newest version.
I tried to download code and compile it but I have errors.
![compiling](https://github.com/txty-io/texterify/assets/136199420/0874f513-6fa9-4ec6-af67-2e0837598a67)
Is there any special way to install the program in a simple way on the new version?
Regards

**Comment by chrztoph** [comment]
Hey, please setup the service using the following instructions: https://docs.texterify.com/installation
We are currently releasing a new version `1.2.1`, but you can also manually set the `TEXTERIFY_TAG` variable in the docker-compose setup to a tag from Dockerhub (see https://hub.docker.com/repository/docker/chrztoph/texterify/tags).

**Comment by ZbruczIT** [comment]
Some logs:

sidekiq_1  | 2023-06-27T18:07:09.813Z pid=1 tid=1vbx class=ImportVerifyWorker jid=bc58e62d8467f10162ca4fcf INFO: start
sidekiq_1  | 2023-06-27T18:07:09.845Z pid=1 tid=1vbx class=ImportVerifyWorker jid=bc58e62d8467f10162ca4fcf INFO:   Disk Storage (0.3ms) Downloaded file from key: n6pvycao4k5b80en08qk59qf5bo4
sidekiq_1  | 2023-06-27T18:07:09.849Z pid=1 tid=1vbx class=ImportVerifyWorker jid=bc58e62d8467f10162ca4fcf elapsed=0.036 INFO: fail
sidekiq_1  | 2023-06-27T18:07:09.850Z pid=1 tid=1vbx WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","args":["1d4dc335-7628-4377-9921-da05db79de6c","605ea1f1-b317-40b5-a1ec-fcfec4944a53","7a7295e7-51c5-4099-8ba8-1fd08e0b4b90"],"class":"ImportVerifyWorker","jid":"bc58e62d8467f10162ca4fcf","created_at":1687889211.1041484,"enqueued_at":1687889229.8119233,"error_message":"ActiveStorage::FileNotFoundError","error_class":"ActiveStorage::FileNotFoundError","failed_at":1687889211.3596373,"retry_count":0},"jobstr":"{\"retry\":true,\"queue\":\"default\",\"args\":[\"1d4dc335-7628-4377-9921-da05db79de6c\",\"605ea1f1-b317-40b5-a1ec-fcfec4944a53\",\"7a7295e7-51c5-4099-8ba8-1fd08e0b4b90\"],\"class\":\"ImportVerifyWorker\",\"jid\":\"bc58e62d8467f10162ca4fcf\",\"created_at\":1687889211.1041484,\"enqueued_at\":1687889229.8119233,\"error_message\":\"ActiveStorage::FileNotFoundError\",\"error_class\":\"ActiveStorage::FileNotFoundError\",\"failed_at\":1687889211.3596373,\"retry_count\":0}"}
sidekiq_1  | 2023-06-27T18:07:09.850Z pid=1 tid=1vbx WARN: ActiveStorage::FileNotFoundError: ActiveStorage::FileNotFoundError
sidekiq_1  | 2023-06-27T18:07:09.851Z pid=1 tid=1vbx WARN: /usr/local/bundle/gems/activestorage-6.1.3.1/lib/active_storage/service/disk_service.rb:145:in `rescue in stream'
sidekiq_1  | /usr/local/bundle/gems/activestorage-6.1.3.1/lib/active_storage/service/disk_service.rb:138:in `stream'
sidekiq_1  | /usr/local/bundle/gems/activestorage-6.1.3.1/lib/active_storage/service/disk_service.rb:29:in `block in download'
sidekiq_1  | /usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `block in instrument'
sidekiq_1  | /usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sidekiq_1  | /usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `instrument'
sidekiq_1  | /usr/local/bundle/gems/activestorage-6.1.3.1/lib/active_storage/service.rb:155:in `instrument'
sidekiq_1  | /usr/local/bundle/gems/activestorage-6.1.3.1/lib/active_storage/service/disk_service.rb:28:in `download'
sidekiq_1  | /usr/local/bundle/gems/activestorage-6.1.3.1/lib/active_storage/downloader.rb:32:in `download'
sidekiq_1  | /usr/local/bundle/gems/activestorage-6.1.3.1/lib/active_storage/downloader.rb:13:in `block in open'
sidekiq_1  | /usr/local/bundle/gems/activestorage-6.1.3.1/lib/active_storage/downloader.rb:24:in `open_tempfile'
sidekiq_1  | /usr/local/bundle/gems/activestorage-6.1.3.1/lib/active_storage/downloader.rb:12:in `open'
sidekiq_1  | /usr/local/bundle/gems/activestorage-6.1.3.1/lib/active_storage/service.rb:90:in `open'
sidekiq_1  | /usr/local/bundle/gems/activestorage-6.1.3.1/app/models/active_storage/blob.rb:276:in `open'
sidekiq_1  | /usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/core_ext/module/delegation.rb:310:in `public_send'
sidekiq_1  | /usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/core_ext/module/delegation.rb:310:in `method_missing'
sidekiq_1  | /usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/core_ext/module/delegation.rb:310:in `public_send'
sidekiq_1  | /usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/core_ext/module/delegation.rb:310:in `method_missing'
sidekiq_1  | /var/www/texterify/app/workers/import_verify_worker.rb:17:in `block in perform'
sidekiq_1  | /usr/local/bundle/gems/activerecord-6.1.3.1/lib/active_record/relation/delegation.rb:88:in `each'
sidekiq_1  | /usr/local/bundle/gems/activerecord-6.1.3.1/lib/active_record/relation/delegation.rb:88:in `each'
sidekiq_1  | /var/www/texterify/app/workers/import_verify_worker.rb:14:in `perform'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:196:in `execute_job'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
sidekiq_1  | /usr/local/bundle/gems/sentry-sidekiq-5.4.2/lib/sentry/sidekiq/sentry_context_middleware.rb:7:in `call'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:143:in `invoke'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:163:in `block in process'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/job_retry.rb:114:in `local'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/rails.rb:14:in `block in call'
sidekiq_1  | /usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
sidekiq_1  | /usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/reloader.rb:72:in `block in wrap'
sidekiq_1  | /usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
sidekiq_1  | /usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/reloader.rb:71:in `wrap'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/rails.rb:13:in `call'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:257:in `stats'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/job_logger.rb:13:in `call'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/job_retry.rb:81:in `global'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/job_logger.rb:39:in `prepare'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:123:in `dispatch'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:162:in `process'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:78:in `process_one'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:68:in `run'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/util.rb:56:in `watchdog'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/util.rb:65:in `block in safe_thread'
web_1      | MYIP(ADDED) - - [27/Jun/2023:18:07:10 +0000] "GET /api/v1/projects/605ea1f1-b317-40b5-a1ec-fcfec4944a53/imports/7a7295e7-51c5-4099-8ba8-1fd08e0b4b90 HTTP/1.1" 304 0 "http://IP_ADRESSS(ADDED BY ME)/dashboard/projects/605ea1f1-b317-40b5-a1ec-fcfec4944a53/imports/7a7295e7-51c5-4099-8ba8-1fd08e0b4b90" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 OPR/99.0.0.0" "-"

**Comment by chrztoph** [comment]
The default database name changed. Try setting `DB_PROD_DATABASE=texterify_production` in your env file and restart the service.

**Comment by ZbruczIT** [comment]
During installation i need to change lines :

# Start the service.
docker volume create --name=texterify-database
docker volume create --name=texterify-assets
docker-compose up

on :



# Start the service.

docker volume create --name=texterify_product

docker volume create --name=texterify-assets

docker-compose up

I am asking because when I am adding your setting in .env file and restart service I have error that Database not exist.


Arkadiusz Budynek
System Admin
di support pl. Sp z o.o.
Centrum Biurowe Podwale
​ul. Malachowskiego 10
61-129Poznan- Poland
***@***.***
W:www.di-support.com
Amtsgericht Frankfurt am Main (Hessen) HRB 77110, UstID-Nr DE 212 131 163, St.-Nr. 40 231 372 46 (Finanzamt Wiesbaden), 
WEEE-Reg.-Nr. DE 85144298, Geschäftsführung: Ralph Naruhn, Florian Festner

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet. 
  
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

**Comment by ZbruczIT** [comment]
I tried to change database name in .env file:

DB_PROD_DATABASE=texterify_production 

But I think it don't work :/

Sorry for any troubles :(

**Comment by ZbruczIT** [comment]
Hello, Do you need any additional informations? ^^

Best regards

**Comment by chrztoph** [comment]
Hey, I was able to reproduce it. I will have another look at it tomorrow. I will keep you updated here.

**Comment by chrztoph** [comment]
The issue should be fixed by updating the docker-compose setup to the latest version.
Fixed with https://github.com/txty-io/texterify-docker-compose-setup/commit/d46d03e48e82b10b941d645433bdb3813eaa54f2
