### ISSUE TITLE
Android and iOS sdk

### ISSUE THREAD

**Issue by hsynkunduz** [txty-io/texterify#169]
Hello what happened to android and iOS sdks their github page giving 404. the links are below

https://github.com/texterify/texterify-android
https://github.com/texterify/texterify-ios

**Comment by chrztoph** [comment]
While archiving they also automatically were set to private which went unnoticed. We made them public again.

**Comment by hsynkunduz** [comment]
does archiving mean they are not working?

**Comment by chrztoph** [comment]
They are working but are no longer actively maintained.
