### ISSUE TITLE
Add plural support

### ISSUE THREAD

**Issue by chrztoph** [txty-io/texterify#28]
Add a new option to activate plural support for keys. On activation show the following fields:
- zero
- one
- two
- few
- many
- other

For Android there is an own data format to export such plural keys.

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <plurals name="demo_plural">
        <item quantity="one">%1$d book</item>
        <item quantity="other">%1$d books</item>
    </plurals>
</resources>
```

https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html

**Comment by Nonouf** [comment]
@chrztoph What's up with plural support? Are you by any chance planning to support it soon? Thanks!

**Comment by chrztoph** [comment]
Yes, we already started developing plural support. Expect it to be ready in January.

**Comment by weakfl** [comment]
There's still no "Zero" option. Any plans to add this any time soon?

**Comment by Filmarchiv** [comment]
Hey, plural support has already been added. Which options are available depends on the language you have chosen (according to the CLDR Language Plural Rules).

**Comment by chrztoph** [comment]
Hey, plural support has already been added. Which options are available depends on the language you have chosen (according to the CLDR Language Plural Rules). The zero options is also available.

**Comment by weakfl** [comment]
> The zero options is also available.

@chrztoph where exactly? 👇 

<img width="194" alt="Screenshot 2023-11-06 at 08 55 05" src="https://github.com/txty-io/texterify/assets/614985/db040117-5ede-4b7a-b885-c1e0a3bd7417">
